#Config File for Atalk
#A Minecraft/Bukkit plugin made by triarry
#
#DO NOT CHANGE THIS LINE
version: 1.2
#
#triarry's github: https://github.com/triarry/Atalk
#

check-for-updates: true
staff:
    members:
    - triarry
    - yourstaffhereandbelow
players:
    mute:
      []